version: '3'
services:
  api1:
    build: ./app
    container_name: api1

  api2:
    build: ./app
    container_name: api2

  nginx:
    image: nginx:latest
    container_name: nginx-lb
    ports:
      - "8080:80"          # Mở port 8080 trên máy bạn
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
